SET ( LIBB64_BUFFERSIZE "16777216" )

IF ( WIN32 )
    SET ( MYLIB_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )

IF ( WIN32 )
    SET ( EPS_SERVER_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )

IF ( WIN32 )
    SET ( EPS_DESKTOP_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )

