SET ( EPS_IPC_PROTOCOL_NAME "EPS" )
SET ( EPS_IPC_PROTOCOL_VERSION_MAJOR "1" )
SET ( EPS_IPC_PROTOCOL_VERSION_MINOR "0" )
SET ( EPS_IPC_PROTOCOL_VERSION "${EPS_IPC_PROTOCOL_VERSION_MAJOR}.${EPS_IPC_PROTOCOL_VERSION_MINOR}" )

SET ( EPS_PRODUCT_COMPANY_NAME "PooyaSokhan(R) English Institute" )
SET ( EPS_PRODUCT_COPYRIGHT_HOLDER "E-PooyaSokhan" )
SET ( EPS_PRODUCT_COPYRIGHT_YEAR "2013" )
SET ( EPS_PRODUCT_COPYRIGHT "(C) ${EPS_PRODUCT_COPYRIGHT_YEAR} ${EPS_PRODUCT_COPYRIGHT_HOLDER}" )
SET ( EPS_PRODUCT_DEVELOPER "Mohammad S. Babaei (info@babaei.net)" )

SET ( EPS_SERVER_PRODUCT_INTERNAL_NAME "EPSServer" )
SET ( EPS_SERVER_PRODUCT_NAME "EPS Server Version" )
SET ( EPS_SERVER_PRODUCT_VERSION_MAJOR "0" )
SET ( EPS_SERVER_PRODUCT_VERSION_MINOR "1" )
SET ( EPS_SERVER_PRODUCT_VERSION_PATCH "0" )
SET ( EPS_SERVER_PRODUCT_DESCRIPTION "The EPS Server" )

SET ( EPS_DESKTOP_PRODUCT_INTERNAL_NAME "EPSDesktop" )
SET ( EPS_DESKTOP_PRODUCT_NAME "EPS Desktop Version" )
SET ( EPS_DESKTOP_PRODUCT_VERSION_MAJOR "0" )
SET ( EPS_DESKTOP_PRODUCT_VERSION_MINOR "1" )
SET ( EPS_DESKTOP_PRODUCT_VERSION_PATCH "0" )
SET ( EPS_DESKTOP_PRODUCT_DESCRIPTION "The EPS Desktop Client" )

IF ( EXISTS "${PROJECT_SOURCE_DIR}/.git" )
    EXEC_PROGRAM ( ${GIT_EXECUTABLE}
        ARGS "--git-dir=\"${PROJECT_SOURCE_DIR}/.git\" --work-tree=\"${PROJECT_SOURCE_DIR}\" describe --always"
        OUTPUT_VARIABLE GIT_SHORT_REVISION_HASH )
    SET ( EPS_SERVER_PRODUCT_VERSION_REVISION ${GIT_SHORT_REVISION_HASH} )
    SET ( EPS_DESKTOP_PRODUCT_VERSION_REVISION ${GIT_SHORT_REVISION_HASH} )
ELSE (  )
    SET ( EPS_SERVER_PRODUCT_VERSION_REVISION "{non-git}" )
    SET ( EPS_DESKTOP_PRODUCT_VERSION_REVISION "{non-git}" )    
ENDIF (  )

SET ( EPS_SERVER_PRODUCT_VERSION "${EPS_SERVER_PRODUCT_VERSION_MAJOR}.${EPS_SERVER_PRODUCT_VERSION_MINOR}.${EPS_SERVER_PRODUCT_VERSION_PATCH} ${EPS_DESKTOP_PRODUCT_VERSION_REVISION}" )

SET ( EPS_DESKTOP_PRODUCT_VERSION "${EPS_DESKTOP_PRODUCT_VERSION_MAJOR}.${EPS_DESKTOP_PRODUCT_VERSION_MINOR}.${EPS_DESKTOP_PRODUCT_VERSION_PATCH} ${EPS_DESKTOP_PRODUCT_VERSION_REVISION}" )

