#ifndef VERSIONINFO_HPP
#define VERSIONINFO_HPP


#define     VERSION_INFO_BUILD_COMPILER         PRODUCT_BUILD_COMPILER
#define     VERSION_INFO_BUILD_DATE             __DATE__ " " __TIME__
#define     VERSION_INFO_BUILD_HOST             PRODUCT_BUILD_HOST
#define     VERSION_INFO_BUILD_PROCESSOR        PRODUCT_BUILD_PROCESSOR
#define     VERSION_INFO_BUILD_SYSTEM           PRODUCT_BUILD_SYSTEM
#define     VERSION_INFO_COPYRIGHT_HOLDER       PRODUCT_COPYRIGHT_HOLDER
#define     VERSION_INFO_COPYRIGHT_YEAR         PRODUCT_COPYRIGHT_YEAR
#define     VERSION_INFO_DEVELOPER              PRODUCT_DEVELOPER
#define     VERSION_INFO_PRODUCT_NAME           PRODUCT_PRODUCT_NAME
#define     VERSION_INFO_PRODUCT_VERSION        PRODUCT_PRODUCT_VERSION


#endif /* VERSIONINFO_HPP */


